/**
 * @file timer.h
 * @brief *Intel 8253* Programmable Interval Timer.
 *
 * @par GitHub
 * https://github.com/Zhuagenborn
 */

#pragma once

#include "kernel/stl/cstdint.h"

namespace io {

//! The number of interrupts generated by the timer per second.
inline constexpr stl::size_t timer_freq_per_second {100};

/**
 * @brief Initialize the timer.
 *
 * @param freq_per_second The number of generated interrupts per second.
 */
void InitTimer(stl::size_t freq_per_second) noexcept;

//! Get the number of ticks after system startup.
stl::size_t GetTicks() noexcept;

//! Whether the timer has been initialized.
bool IsTimerInited() noexcept;

}  // namespace io